"""Add delayed actions

Revision ID: 7887609c4179
Revises: cc98ae4b1a4f
Create Date: 2019-04-16 23:23:08.102511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import bothanasius

# revision identifiers, used by Alembic.
revision = '7887609c4179'
down_revision = 'cc98ae4b1a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'delayed_actions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', bothanasius.db.base.DateTime(), nullable=False),
        sa.Column('expires', bothanasius.db.base.DateTime(), nullable=False),
        sa.Column('event', sa.String(), nullable=False),
        sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_delayed_actions_expires'), 'delayed_actions', ['expires'], unique=False
    )
    op.drop_table('delayed_mutes')
    op.create_unique_constraint(
        'linked_roles_guild_id_role_id_key', 'linked_roles', ['guild_id', 'role_id']
    )
    op.drop_index('linked_roles_parent_role_idx', table_name='linked_roles')
    op.drop_column('linked_roles', 'parent_role_id')
    op.create_unique_constraint(
        'self_roles_guild_id_role_id_key', 'self_roles', ['guild_id', 'role_id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('self_roles_guild_id_role_id_key', 'self_roles', type_='unique')
    op.add_column(
        'linked_roles',
        sa.Column('parent_role_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        'linked_roles_parent_role_idx',
        'linked_roles',
        ['guild_id', 'parent_role_id'],
        unique=False,
    )
    op.drop_constraint(
        'linked_roles_guild_id_role_id_key', 'linked_roles', type_='unique'
    )
    op.create_table(
        'delayed_mutes',
        sa.Column('guild_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('member_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint('guild_id', 'member_id', name='delayed_mutes_pkey'),
    )
    op.drop_index(op.f('ix_delayed_actions_expires'), table_name='delayed_actions')
    op.drop_table('delayed_actions')
    # ### end Alembic commands ###
