"""Add time out role to guild prefs

Revision ID: b7fae3499a2b
Revises: 7887609c4179
Create Date: 2019-04-17 17:05:13.102578

"""
from alembic import op
import sqlalchemy as sa
import botus_receptus


# revision identifiers, used by Alembic.
revision = 'b7fae3499a2b'
down_revision = '7887609c4179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'guild_prefs',
        sa.Column('time_out_role', botus_receptus.gino.base.Snowflake(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_prefs', 'time_out_role')
    # ### end Alembic commands ###
